<style type="text/css">.nav li, .bottom-nav li {width: 33%;}</style>
<ul class="tabs">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
    <li><a class="active-nav" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'people', 'action' => 'index')) ?>">People</a></li>
</ul>
<ul class="nav">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Basic</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'contact-info')) ?>">Contact</a></li>
    <li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'course-info')) ?>">Course</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'status')) ?>">Status</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'settings')) ?>">Settings</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout')) ?>">Logout</a></li>
</ul>
<div class="content">
    <?php if ($this->person): $person = $this->person; $course = $this->course ?>
    <h1>Course Info<span class="right"><a class="icon" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'course-info', 'id' => $this->person ? $this->person->id : ''), null, true) ?>"><img alt="Preview" src="<?php echo $this->baseUrl('/styles/icons/16/next.png') ?>" /></a></span></h1>
    <?php if ($this->message): ?>
    <p class="ok"><?php echo $this->message ?></p>
    <?php endif ?>
<table class="vertical">
<tr><th>Course:</th><td><?php echo $course ? $course['course'] ? $this->escape($course['course']) : 'Not set' : 'Not set' ?><br /><a class="icon" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'edit-course'), null, true) ?>"><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>"</a></td></tr>
<tr><th>Graduation Year:</th><td><?php echo $course? $course['year'] ? $this->escape($course['year']) : 'Not set' : 'Not set' ?><br /><a class="icon" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'edit-course'), null, true) ?>"><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>"</a></td></tr>
</table>
    <div class="tips">
        <p><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>" /> - Edit a field<img alt="preview" src="<?php echo $this->baseUrl('/styles/icons/16/next.png') ?>" /> - Preview</p>
    </div>
    <?php else: ?>
    <p class="errors">An error occurred and your profile could not be retrieved. Please try again later.</p>
    <?php endif ?>
</div>
<ul class="bottom-nav">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'status')) ?>">Status</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'settings')) ?>">Settings</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout')) ?>">Logout</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Basic</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'contact-info')) ?>">Contact</a></li>
    <li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'course-info')) ?>">Course</a></li>
</ul>