<style type="text/css">.nav li, .bottom-nav li {width: 33%;}</style>
<ul class="tabs">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
    <li><a class="active-nav" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'people', 'action' => 'index')) ?>">People</a></li>
</ul>
<ul class="nav">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Basic</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'contact-info')) ?>">Contact</a></li>
    <li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'course-info')) ?>">Course</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'status')) ?>">Status</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'settings')) ?>">Settings</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout')) ?>">Logout</a></li>
</ul>
<div class="content">
    <h2>Course</h2>
    <?php if ($this->message) { ?>
    <p class="ok"><?php echo $this->message ?></p>;
    <?php } if ($this->error) { ?>
    <ul class="errors">
        <li><?php echo $this->error ?></li>
    </ul>
    <?php } echo $this->form ?>
    <div class="tips">
            Year entered refers to the graduation year.
           <p> You can only be added to a class once.</p>
    </div>
</div>
<ul class="bottom-nav">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'status')) ?>">Status</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'settings')) ?>">Settings</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout')) ?>">Logout</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Basic</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'contact-info')) ?>">Contact</a></li>
    <li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'course-info')) ?>">Course</a></li>
</ul>