<style type="text/css">
	.nav li {width: 33%;}
	.bottom-nav li {width: 33%}
</style>
<ul class="tabs">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index')) ?>">Home</a></li>
    <li><a class="active-nav" href="<?php echo $this->url(array('controller'=>'index','action'=>'index')) ?>">Wisdom</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
</ul>
<ul class="nav">
    <li><a class="active" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'bizads')) ?>">Business</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'classifieds', 'action'=>'index')) ?>">Classified</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'bizads')) ?>">Category</a></li>
</ul>
<ul class="nav">
    <li><a href="<?php echo $this->url(array('controller'=>'mybizads','action'=>'index')) ?>">My ads</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'businesses','action'=>'viewproducts')) ?>">Products</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'login','action'=>'logout')) ?>">Logout</a></li>
</ul>
<div class="content">
	<?php if(isset($this->form)): ?> 
		<?php echo $this->form;?>
	<?php endif;?>
	<?php if(!empty($this->category_name)):?>
		<h1 align="center"><?php echo $this->category_name ?>: businesses</h1>
	<?php endif;?>
	<?php if(!empty($this->businesses)){?>
		<table class="vertical-image">
		<?php foreach ($this->businesses as $business): ?>
			<tr>
            <th><img alt="<?php echo $business['name']?>'s profile" class="framed" 
                     src="<?php echo $this->baseUrl('/uploads/business/'.$business['logo'])?>" /></th>
            <td>
                <b><?php echo $this->escape($business['name'])?></b>
                <p><?php echo $business['location']?></p>
                <p><?php echo $business['email'].', '.$business['mobile']?></p>
                <span class="meta"><a href="<?php echo $this->url(array('controller'=>'businesses', 'action'=>'profile','bizid'=>$business['id'])) ?>">detailed profile</a></span>
            </td>
        	</tr>		
		<?php endforeach;?>
		</table>
		<?php echo $this->businesses; ?>
	<?php } else{?>
			<div class="errors">There are no businesses under <?php echo $this->category_name ?></div>
	<?php }?>
</div>
<div align="center" class="tips">
	<p>You can view all products offered <span class="meta"><a href="<?php echo $this->url(array('controller'=>'businesses', 'action'=>'viewproducts'))?>">here</a></span></p>
</div>
<ul class="bottom-nav">		
	<li><a href="<?php echo $this->url(array('controller'=>'events','action'=>'index')) ?>">Events</a></li>
	<li><a href="<?php echo $this->url(array('controller'=>'experiences','action'=>'namedetails')) ?>">Experiences</a></li>
	<li><a>Maps</a></li>
</ul>
