<style type="text/css">.tabs li {width:50%}</style>
<ul class="tabs">
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'about-us', 'action' => 'index')) ?>">About Us</a></li>
</ul>
<div class="content"><p class="entry">This page is currently under develoment, please check back later.</p></div>