<style type="text/css">
.nav li, .bottom-nav li {width: 33%;}
</style>
<ul class="tabs">
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true) ?>">Home</a></li>
<li><a class="active-nav" href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'index', 'action' => 'index'), null, true) ?>">Routes</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index'), null, true) ?>">Profile</a></li>
</ul>
<ul class="nav">
<li><a href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'index', 'action' => 'index'), null, true) ?>">Subscribed</a></li>
<li><a class="active" href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'routes', 'action' => 'my-routes'), null, true) ?>">Mine</a></li>
<li><a href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'routes', 'action' => 'index'), null, true) ?>">All</a></li>
</ul>
<div class="content">
<h2>You Sure?</h2>
<p>Please confirm that you want to delete <?php echo $this->name ? '<b>'. $this->escape($this->name) . '</b>' : 'this route' ?>. <?php echo $this->escape($this->subs) ?> users are subscribed to this route.</p>
<p><a class="button" href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'routes', 'action' => 'delete', 'id' => $this->id), null, true) ?>">Delete</a>&nbsp;<a class="button" href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'routes', 'action' => 'my-routes'), null, true) ?>">Cancel</a></p>
</div>
<ul class="bottom-nav">
<li><a href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'index', 'action' => 'index'), null, true) ?>">Subscribed</a></li>
<li><a class="active" href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'routes', 'action' => 'my-routes'), null, true) ?>">Mine</a></li>
<li><a href="<?php echo $this->url(array('module' => 'traffic-updates', 'controller' => 'routes', 'action' => 'index'), null, true) ?>">All</a></li>
</ul>