<?php if ($this->pageCount): ?>
<div class="paginationControl" align="center">

<!-- First page link -->
<?php if (isset($this->previous)): ?>
	<a href="<?php echo $this->url(array('page' => $this->first)); ?>">
		&laquo;
	</a>
<?php else: ?>
	<span class="disabled">&laquo;</span> 
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
	<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
		&lsaquo;
	</a>
<?php else: ?>
	<span class="disabled">&lsaquo;</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
		<a href="<?php echo $this->url(array('page' => $page)); ?>">
			<?php echo $page; ?>
		</a> |
	<?php else: ?>
		<span id="current_page"><?php echo $page; ?></span> |
	<?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
	<a href="<?php echo $this->url(array('page' => $this->next)); ?>">
		&rsaquo;
	</a>
<?php else: ?>
	<span class="disabled">&rsaquo;</span>
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->last)); ?>">
	&raquo;
</a>
<?php else: ?>
	<span class="disabled">&raquo;</span>
<?php endif; ?>

</div>
<?php endif; ?>
