<?php

class Yearbook_Form_Classlist extends Zend_Form {

    public function init() {
        $course=new Zend_Form_Element_Select('course');
        $course->setlabel('Course')
                ->addMultiOptions(array('B.SC. (AGRICULTURE)'=>'B.SC. (AGRICULTURE)','B.SC. (FOOD SCIENCE&TECHN)'=>'B.SC. (FOOD SCIENCE & TECHNOLOGY)','B.SC. (RANGE MANAGEMENT)'=>'B.SC. (RANGE MANAGEMENT)',
                'BSC.MGNT OF AGROECOSYSTEMS&ENVIRON'=>'BSC.MGNT OF AGROECOSYSTEMS&ENVIRON','B.SC.(AGRIC EDUCATION)'=>'B.SC.(AGRIC EDUCATION)','B.SC. (AGRIBUSINESS MNGT)'=>'B.SC. (AGRIBUSINESS MNGT)','B.SC.(FOOD SCIENCE)'=>'B.SC.(FOOD SCIENCE)','BACHELOR OF ARCHITECTURE'=>'BACHELOR OF ARCHITECTURE','B.A (BUILDING ECONOMICS)'=>'B.A (BUILDING ECONOMICS)',
                'B.A.(LAND ECONOMICS)'=>'B.A.(LAND ECONOMICS)','B.A. (DESIGN)'=>'B.A. (DESIGN)','B.A. (PLANNING)'=>'B.A. (PLANNING)','B.A(URBAN PLANNING)'=>'B.A(URBAN PLANNING)','BACHELOR OF ARTS'=>'BACHELOR OF ARTS','BACHELOR OF ARTS SOCIALWORK'=>'BACHELOR OF ARTS SOCIALWORK','BACHELOR OF PSYCHOLOGY'=>'BACHELOR OF PSYCHOLOGY','BACHELOR OF COMMERCE'=>'BACHELOR OF COMMERCE','BACHELOR OF EDUCATION(ARTS)'=>'BACHELOR OF EDUCATION(ARTS)',
                'BACHELOR OF EDUCATION(SCIENCE)'=>'BACHELOR OF EDUCATION(SCIENCE)','BACHELOR OF EDU(EARLY CHILDHOOD)'=>'BACHELOR OF EDU(EARLY CHILDHOOD)','B.SC.(SURVEYING)'=>'B.SC.(SURVEYING)','B.SC.(CIVIL ENGINEERING)'=>'B.SC.(CIVIL ENGINEERING)','B.SC.(ELECTRICAL ENGINEERING)'=>'B.SC.(ELECTRICAL ENGINEERING)','B.SC.(MECHANICAL ENGINEERING)'=>'B.SC.(MECHANICAL ENGINEERING)',
                'B.SC.(GEOSPATIAL ENG)'=>'B.SC.(GEOSPATIAL ENG)','B.SC.(ENVIRON&BIOSYSTEMS ENG)'=>'B.SC.(ENVIRON&BIOSYSTEMS ENG)','BACHELOR OF LAW'=>'BACHELOR OF LAW','BSC (BIOCHEMISTRY)'=>'BSC (BIOCHEMISTRY)','B.SC. ANATOMY'=>'B.SC. ANATOMY','B.SC. MEDICAL PHYSIOLOGY'=>'B.SC. MEDICAL PHYSIOLOGY','BACHELOR OF MEDICINE'=>'BACHELOR OF MEDICINE','BACHELOR OF SURGERY'=>'BACHELOR OF SURGERY','B.SC.(NURSING)'=>'B.SC.(NURSING)',
                'B.SC.ACTUARIAL SCIENCE'=>'B.SC.ACTUARIAL SCIENCE','B.SC. INDUSTRIAL CHEMISTRY'=>'B.SC. INDUSTRIAL CHEMISTRY','B.SC. MATHEMATICS'=>'B.SC. MATHEMATICS','B.SC.(METEOROLOGY)'=>'B.SC.(METEOROLOGY)','B.SC.(BIOLOGY)'=>'B.SC.(BIOLOGY)','B.SC.(GEOLOGY)'=>'B.SC.(GEOLOGY)','BSC. ANALYTICAL CHEMISTRY'=>'BSC. ANALYTICAL CHEMISTRY','BACHELOR OF SCIENCE'=>'BACHELOR OF SCIENCE','BSC. MICRO&BIOTECH'=>'BSC. MICRO&BIOTECH',
                'BSC. ENVIRON GEOSCIENCE'=>'BSC. ENVIRON GEOSCIENCE','B.SC(MICROPROCESSOR TECH)'=>'B.SC(MICROPROCESSOR TECH)','B.SC. ENVIRON CONSERVATION'=>'B.SC. ENVIRON CONSERVATION','BSC. ENVIRON CHEMISTRY'=>'BSC. ENVIRON CHEMISTRY','B.SC. STATISTICS'=>'B.SC. STATISTICS','BACHELOR OF VET MED'=>'BACHELOR OF VET MED',
                'B.SC.(BIO-MEDICAL TECH)','B.A. (JOURNALISM)'=>'B.A. (JOURNALISM)','B.ED. EXTERNAL STUDIES'=>'B.ED. EXTERNAL STUDIES','B.A (ANTHROPOLOGY)'=>'B.A (ANTHROPOLOGY)','B.A (GENDER&DEV STUDIES)'=>'B.A (GENDER&DEV STUDIES)','BSC. COMPUTER SCIENCE'=>'BSC. COMPUTER SCIENCE',
                'BACHELOR OF PHARMACY'=>'BACHELOR OF PHARMACY','BACHELOR OF DENTAL SURGERY'=>'BACHELOR OF DENTAL SURGERY','BED (GEOLOGY MAJOR)'=>'BED (GEOLOGY MAJOR)','B.SC. ATMOSPHERIC SCIENCE'=>'B.SC. ATMOSPHERIC SCIENCE','BACHELOR OF CONSTRUC$MNGT'=>'BACHELOR OF CONSTRUC$MNGT','BACHELOR OF QUANTITY SURVEYING'=>'BACHELOR OF QUANTITY SURVEYING','B.SC. WILDLIFE MNGNT'=>'B.SC. WILDLIFE MNGNT','BACHELOR OF ARTS'=>'BACHELOR OF ARTS','B.A. POLITICAL SCIENCE'=>'B.A. POLITICAL SCIENCE','B.A PUBLIC ADMIN'=>'B.A PUBLIC ADMIN',
                'B.A HISTORY'=>'B.A HISTORY','B.ED(DISTANCE LEARNING)'=>'B.ED(DISTANCE LEARNING)','BSC GEOLOGY(DISTANCE LEARNING)'=>'BSC GEOLOGY(DISTANCE LEARNING)','B.SC.ASTRONOMY&ASTROPHYSICS'=>'B.SC.ASTRONOMY&ASTROPHYSICS','B.SC. IN PHYSICS'=>'B.SC. IN PHYSICS','BACHELOR OF ECONOMICS'=>'BACHELOR OF ECONOMICS','BACHELOR OF ECON&STATS'=>'BACHELOR OF ECON&STATS'
                ))
                ->setRequired(true)
                ->addFilter('StripTags')
                ->addValidator('NotEmpty');

        $array_year=array();
        $current_year=date("Y");
        for($count=0;$count<15;$count++) {
            $value=(int)$current_year+$count;
            array_push($array_year, array('key'=>$value,'value'=>$value));
        }

        $year=new Zend_Form_Element_Select('year');
        $year->setlabel('Graduation Year')
                ->addMultiOptions($array_year)
                ->setRequired(true)
                ->addFilter('StripTags')
                ->addValidator('NotEmpty');




        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setIgnore(true)->setRequired(false)->setLabel('View');
        $this->addElements(array($course,$year,$submit))
             ->setDecorators(array(
                'FormElements',
                'Form'
           ));


    }


}

