<style type="text/css">
.nav li {width:50%;}
</style>
<ul class="tabs">
<li><a href="/Sizzle/public/">Home</a></li>
<li><a class="active-nav">File sharing</a></li>
<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'login','action'=>'logout')); ?>">Logout</a></li>
</ul>
<ul class="nav">
<li><a href="<?php echo $this->url(array('module'=>'filesharing','controller'=>'Download','action'=>'index')); ?>">Downloads</a></li>
<li><a class="active" href="<?php echo $this->url(array('module'=>'filesharing','controller'=>'index','action'=>'register')); ?>">Uploads</a></li>
</ul>
<?php 
foreach ($this->all as $all)
{
    echo "<a href='<li>'.$this->escape($all->name).'</li>'";

}
?>
    <a href="<?php ///echo $this->url(array('module'=>'default','controller'=>'index','action'=>'getregisterd'));?>"></a>