<ul class="tabs"><li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a class="active-nav" href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'forums'),'default',true) ?>">Forums</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
</ul><?php if($this->role == 1) : ?><style type="text/css">.nav li{width: 25%;} .bottom-nav li{width: 25%;}</style><ul class="nav"><li><a class="active" href="">Profile</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id'],'title'=>$this->group['title']), 'default', true); ?>">Members</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'requests','module'=>'forums','id'=>$this->group['id'],), 'default', true); ?>">Requests</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'notify','module'=>'forums','groupID'=>$this->group['id']), 'default', true); ?>">Notify</a></li>
</ul><?php elseif($this->role == 0) : ?><style type="text/css">.nav li{width: 33%;} .bottom-nav li{width: 33%;}</style><ul class="nav"><li><a class="active" href="">Profile</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id'],'title'=>$this->group['title']), null, true); ?>">Members</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'notify','module'=>'forums','groupID'=>$this->group['id']), 'default', true); ?>">Notify</a></li>
</ul> <?php else : ?><style type="text/css">.nav li{width: 50%;} .bottom-nav li{width: 50%;}</style><ul class="nav"><li><a class="active" href="">Profile</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id'],'title'=>$this->group['title']), null, true); ?>">Members</a></li></ul> <?php endif; ?>
<div class="content"><?php if(isset ($this->group)) {$title = $this->group['title'].": Profile";} else {$title = "Group Profile";}?>
<div id="logo"><center><?php if($this->group['type'] == 'closed') : ?><img alt="<?php echo $title; ?>" src="<?php echo $this->baseUrl('/styles/icons/forums/closedGroupProfile.jpg') ?>" />
<?php else : ?><img alt="<?php echo $title; ?>" src="<?php echo $this->baseUrl('/styles/icons/forums/groupProfile.jpg') ?>" /><?php endif; ?>
<h1><?php echo $title; ?></h1></center></div><br/><br/><br/><?php if(isset ($this->error)) : ?><p class="errors"><?php echo $this->error; ?></p><?php endif; ?><?php if(isset ($this->form)) : ?><?php echo $this->form; ?><?php else: ?>
<p><b style="font-size: 1.1em; text-transform: capitalize">Title:</b> <?php echo $this->group['title']; ?></p>
<p style="text-transform: capitalize;"> <b style="font-size: 1.1em;">Type:</b> <?php echo $this->group['type']; ?></p>
<p> <b style="font-size: 1.1em; text-transform: capitalize">Members:</b> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id']), 'default', true); ?>"><?php echo $this->group['members']; ?></a></p>
<p> <b style="font-size: 1.1em; text-transform: capitalize">Creator:</b> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'person','module'=>'forums','persID'=>$this->group['created_by']), 'default', true); ?>"> view profile </a> </p>
<p> <b style="font-size: 1.1em; text-transform: capitalize">Date Created:</b> <?php echo $this->group['created_at']; ?></p>
<p> <b style="font-size: 1.1em; text-transform: capitalize">Description:</b> <?php echo $this->group['description']; ?></p>
<hr size="5" align="center"/><?php if($this->role == 1) : ?><p> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'update','module'=>'forums', 'groupID'=>$this->group['id'], 'title'=>$this->group['title'], 'type'=>$this->group['type'], 'description'=>$this->group['description']), 'default', true); ?>"> Update group </a> </p>
<p> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'deletegroup','module'=>'forums','groupID'=>$this->group['id'],'title'=>$this->group['title']), 'default', true); ?>"> Delete Group </a> </p>
<?php endif; ?><?php if($this->role != 10) : ?><div align="right"> <a href="<?php echo $this->url(array('controller'=>'thread', 'action'=>'get-group-threads', 'module'=>'forums', 'id'=>$this->group['id']), 'default', true);?>"> View Discussions </a> </div><?php endif; ?>
<?php if($this->role == 10) : ?><p> <a href="<?php echo $this->url(array('controller'=>'index','action'=>'join','module'=>'forums','groupID'=>$this->group['id'], 'type'=>$this->group['type']), 'default', true); ?>"> Join group </a> </p><?php endif; ?>
<?php endif; ?></div><?php if($this->role == 1) : ?><ul class="bottom-nav"><li><a class="active" href="">Profile</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id'],'persID'=>$this->group['created_by'],'type'=>$this->group['type']), 'default', true); ?>">Members</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'requests','module'=>'forums','id'=>$this->group['id'],), 'default', true); ?>">Requests</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'notify','module'=>'forums','groupID'=>$this->group['id']), 'default', true); ?>">Notify</a></li>
</ul><?php elseif($this->role == 0) : ?><ul class="bottom-nav"><li><a class="active" href="">Profile</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id'],'persID'=>$this->group['created_by'],'type'=>$this->group['type']), 'default', true); ?>">Members</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'notify','module'=>'forums','groupID'=>$this->group['id']), 'default', true); ?>">Notify</a></li>
</ul><?php else : ?><ul class="bottom-nav"><li><a class="active" href="">Profile</a></li><li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'members','module'=>'forums','id'=>$this->group['id'],'persID'=>$this->group['created_by'],'type'=>$this->group['type']), 'default', true); ?>">Members</a></li></ul><?php endif; ?>