<style type="text/css"> .nav li{width: 25%;} .bottom-nav li{width: 25%;} </style><ul class="tabs"><li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a class="active-nav" href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'forums'),'default',true) ?>">Forums</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
</ul><ul class="nav"><li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'forums'),'default',true) ?>">Home</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'new','module'=>'forums'), 'default', true); ?>">Create</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'available-groups','module'=>'forums'), 'default', true); ?>">Public</a></li>
<li><a class="active" href="<?php echo $this->url(array('controller'=>'index','action'=>'allgroups','module'=>'forums'), 'default', true); ?>">Search</a></li>
</ul><div class="content"><div id="logo"><center><img alt="Group Search Results" src="<?php echo $this->baseUrl('/styles/icons/forums/results.png') ?>" /><h1>Group(s) Search Results</h1></center></div><br/><br/><br/>
<?php if(isset ($this->error)) { ?><p class="errors"><?php echo $this->error; ?></p><?php } ?><?php if (count($this->paginator)) : ?><table align="center" class="vertical-image">
<?php foreach ($this->paginator as $myGroup): ?><tr><th align="center">
<?php if ($myGroup->getGroupType() == 'closed') : ?><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'profile', 'module'=>'forums', 'id'=>$myGroup->id), null, true);?>"><img alt="Group" align="middle" src="<?php echo $this->baseUrl('/styles/icons/forums/closed.jpg') ?>"></a>
<?php else : ?><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'profile', 'module'=>'forums', 'id'=>$myGroup->id), null, true);?>"><img alt="Group" align="middle" src="<?php echo $this->baseUrl('/styles/icons/forums/group.jpg') ?>"></a>
<?php endif; ?></th><td><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'profile', 'module'=>'forums', 'id'=>$myGroup->id), null, true);?>"><b><?php echo $myGroup->getTitle(); ?></b></a>
<div class="entry"><?php echo $myGroup->getDescription() ? strlen($myGroup->getDescription()) > 50 ? '<p>' . $this->escape(substr($myGroup->getDescription(), 0, 50) . '...') . '</p>' : '<p>'. $this->escape($myGroup->getDescription()) . '</p>' : '' ?>
<p class="meta">Members: <span class="meta"><?php echo $myGroup->getNumberOfMembers(); ?></span> | Created: <span class="meta"><?php $date = new Application_Model_Date(); echo $date->relativeTime($myGroup->getCreatedAt()); ?></span></p>
</div></td></tr><?php endforeach ?></table><?php else : ?><p>No group matches your search criteria</p><?php endif; ?><?php echo $this->paginator; ?></div><ul class="bottom-nav">
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'forums'),'default',true) ?>">Home</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'new','module'=>'forums'), 'default', true); ?>">Create</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'available-groups','module'=>'forums'), 'default', true); ?>">Public</a></li>
<li><a class="active" href="<?php echo $this->url(array('controller'=>'index','action'=>'allgroups','module'=>'forums'), 'default', true); ?>">Search</a></li></ul>