<style type="text/css"> .nav li{width: 50%;} .bottom-nav li{width: 50%;} </style><ul class="tabs"><li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a class="active-nav" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'forums'), 'default', true) ?>">Forums</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li></ul>
<ul class="nav"><li><a class="active" href="<?php echo $this->url(array('controller'=>'thread','action'=>'get-group-threads','module'=>'forums'),null,true) ?>">Group</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'thread','action'=>'get-public-threads','module'=>'forums'),null,true) ?>">Public</a></li></ul>
<?php echo "Sorry an error occured";?>
<ul class="bottom-nav"><li><a class="active" href="<?php echo $this->url(array('controller'=>'thread','action'=>'get-group-threads','module'=>'forums'),null,true) ?>">Group</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'thread','action'=>'get-public-threads','module'=>'forums'),null,true) ?>">Public</a></li></ul>