<style type="text/css">
    .bottom-nav li{width: 33%;}
</style>
<?php include 'menu.phtml';?>
<div class="content"><img  alt="Campus Life" class="framed" height="24" src="<?php echo $this->baseUrl('/styles/icons/16/Campus.png')?>" width="24"/>
<span style="display: inline-block;width:auto"><h1>add comment</h1></span>
<?php echo $this->form; ?>
</div>
<div class="bottom-nav">
	<li><a href="<?php echo $this->url(array('controller'=>'events','action'=>'index')) ?>">Events</a></li>
	<li><a href="<?php echo $this->url(array('controller'=>'exps','action'=>'index')) ?>">Experiences</a></li>
	<li><a>Maps</a></li></div>