<style type="text/css">
	.bottom-nav li {width:33%;}
</style>
<?php include 'menu.phtml';?>
<div class="content"><img  alt="Campus Life" class="framed" height="24" src="<?php echo $this->baseUrl('/styles/icons/16/Campus.png')?>" width="24"/>
<span style="display: inline-block;width:auto"><h1>Share  Experience</h1></span>
<?php if (isset($this->msg)) {/* Display Success message */?>
<div class="ok"><?php echo $this->msg; } ?></div>
<?php echo $this->form;?>
<div class="tips">
	Kukuyu,Computer Science,kitchen1,Prefabs are examples of Titles</div>
<div class="bottom-nav">	
	<li><a href="<?php echo $this->url(array('controller'=>'events','action'=>'index')) ?>">Events</a></li>
	<li><a href="<?php echo $this->url(array('controller'=>'exps','action'=>'index')) ?>">Experiences</a></li>
	<li><a>Maps</a></li></div></div>