<style type="text/css">
	.nav li {width: 33%;}
	.bottom-nav li {width: 33%}
</style>
<ul class="tabs">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index')) ?>">Home</a></li>
    <li><a class="active-nav" href="<?php echo $this->url(array('controller'=>'index','action'=>'index')) ?>">Wisdom</a></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
</ul>
<ul class="nav">
    <li><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'bizads')) ?>">Business</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'classifieds', 'action'=>'index')) ?>">Classified</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'allbusinesses')) ?>">All</a></li>
</ul>
<ul class="nav">
	<li><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'bizads')) ?>">Business</a></li>
    <li><a href="<?php echo $this->url(array('controller'=>'mybizads','action'=>'index')) ?>">My ads</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'login','action'=>'logout')) ?>">Logout</a></li>
</ul>
<div class="content">
<h1 align="center">upload business image</h1>
	<?php if(!empty($this->message)):?>
		<?php echo $this->message;?>
	<?php endif;?>
	<?php if(isset($this->form)):?>
		<?php echo $this->form;?>
	<?php endif;?>
</div>
<div align="center" class="tips">
	<p>Upload limit is 10mb. Formats .jpeg, .jpg, .png, .gif</p>
</div>
<ul class="bottom-nav">
	<li><a href="<?php echo $this->url(array('controller'=>'businesses','action'=>'profile','bizid'=>$this->business_id)) ?>">Back</a></li>	
	<li><a href="<?php echo $this->url(array('controller'=>'events','action'=>'index')) ?>">Events</a></li>
	<li><a href="<?php echo $this->url(array('controller'=>'experiences','action'=>'namedetails')) ?>">Experiences</a></li>
</ul>