<style type="text/css">
	.tabs li {width: 50%;}
	.bottom-nav li {width: 33%;}
</style>
<ul class="tabs">
	<li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'index', 'action'=>'index')) ?>">Home</a></li>
    <li><a class="active" href="<?php echo $this->url(array('module'=>'default','controller' => 'login', 'action'=>'recoverpassword')) ?>">Password recovery</a></li>
</ul>
<div class="content">
<h2 align="center">recover your password</h2>
<?php if(!empty($this->error)):?>
	<div class="errors">
		<?php echo $this->error; ?>
	</div>
<?php endif;?>
	<?php 
	if(isset($this->form)){
		echo $this->form;
	}
	?>
</div>
<div align="center" class="tips">
	<p>To recover your password enter your email address used during signup. You will then receive an email with your login details</p>
</div>	
<ul class="bottom-nav">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'index','action'=>'index')) ?>">Home</a></li>
    <li><a class="active" href="<?php echo $this->url(array('module'=>'default','controller' => 'login', 'action'=>'index')) ?>">Login</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'sign-up','action'=>'index')) ?>">Sign Up</a></li>
</ul>