<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Nairobi Sizzle</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link href="<?php echo $this->baseUrl('/styles/mobile/default/style.css') ?>" rel="stylesheet" type="text/css" charset="utf-8" />
<link href="<?php echo $this->baseUrl('favicon.ico') ?>" rel="icon" type="image/x-icon" />
<link href="<?php echo $this->baseUrl('favicon.ico') ?>" rel="Shortcut Icon" />
</head>
<body>
<div id="header"><div id="logo"><img alt="Nairobi Sizzle logo" src="<?php echo $this->baseUrl('/styles/logos/nrbsizzle.png') ?>" /><?php if ($this->isUserLogged): ?><a class="icon" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout'), null, true)?>" ><img alt="Logout" src="<?php echo $this->baseUrl('/styles/icons/16/user_remove.png') ?>" /></a><?php endif ?></div></div>
<div id="wrap"><?php echo $this->layout()->content ?></div>
<div id="footer">
<ul class="footer">
<li><a href="<?php echo $this->url(array('controller' => 'help', 'action' => 'index')) ?>">Help</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'about-us', 'action' => 'index'), null, true) ?>">About</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'feedback', 'action' => 'index'), null, true) ?>">Feedback</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'terms', 'action' => 'index'), null, true) ?>">Terms</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'privacy-policy', 'action' => 'index'), null, true) ?>">Privacy</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'credits', 'action' => 'index'), null, true) ?>">Credits</a></li>
</ul>
<div class="copyright"><p>Viewing: <b>Mobile version</b> (Desktop version coming soon!)</p><p>&copy; 2010 Nairobi Sizzle</p><p>University of Nairobi</p></div>
</div>
</body>
</html>