<style type="text/css">
    /*override global nav settings*/
    .nav li {width: 33%;}
    .bottom-nav li{width: 33%;}
</style><ul class="tabs"><li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a class="active-nav" href="<?php  echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'index'));?>">Yearbook</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'login','action'=>'logout'));?>">Logout</a></li>
</ul><ul class="nav"><li><a class="active" href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'jobsmenu'));?> ">Jobs</a></li>
<li><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'expmenu'));?>">Experiences</a></li>
<li><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'tipsmenu'));?>">Tips</a></li>
</ul><div class="content"><center><h1>Job Network Home  </h1></center><?php if(($this->message)){?><div class="ok"><?php echo $this->message;?></div><?php }?>
<table><tr><td><img alt="jobslogo" align='left' src="<?php echo $this->baseUrl('/styles/icons/search2.jpg') ?>" />
<div class="tips">Tired of hustling for a job?<br />Seen a job and want to tell others?<br />Or simply looking for CV writing & Interview tips?...</div></td></tr></table>
<table ><tr><td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'postjob'));?>">Post Job</a></td>
<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'postjob'));?>"><img alt="go" src="<?php echo $this->baseUrl('/styles/icons/16/next.png') ?>" /></a></td>
<td>| <a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'Availjobs'));?>">View Available Jobs</a> </td>
<td><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'Availjobs'));?>"><img alt="go" src="<?php echo $this->baseUrl('/styles/icons/16/next.png') ?>" /></a></td></tr></table>
<div class="tips">Select Post Job to submit a new job or else View Available Jobs .</div>
</div><ul class="bottom-nav">
     <li><a class="active" href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'jobsmenu'));?> ">Jobs</a></li>
     <li><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'expmenu'));?>">Experiences</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'tipsmenu'));?>">Tips</a></li>

</ul>