 <style type="text/css">
    /*override global nav settings*/
    .nav li, .bottom-nav li {width: 33%;}
</style>
<ul class="tabs">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
    <li><a class="active-nav" href="<?php echo $this->url(array('module'=>'Yearbook','controller' => 'index', 'action' => 'index')) ?>">Yearbook</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'login', 'action' => 'logout')) ?>">Logout</a></li>
</ul>
<ul class="nav">
     <li><a href="<?php echo $this->url(array(  'action' => 'index')) ?>">Class</a></li>
     <li><a href="<?php echo $this->url(array(  'action' => 'list')) ?>">All</a></li>
     <li><a href="<?php echo $this->url(array(  'action' => 'jobsmenu')) ?>">Job network</a></li>
</ul>