<style type="text/css">
    /*override global nav settings*/
    .nav li {width: 33%;}
    .bottom-nav li{width: 33%;}
</style><ul class="tabs"><li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a class="active-nav" href="<?php  echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'index'));?>">Yearbook</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'login','action'=>'logout'));?>">Logout</a></li>
</ul><ul class="nav"><li><a  href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'jobsmenu'));?> ">Jobs</a></li>
<li><a class="active"href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'expmenu'));?>">Experiences</a></li>
<li><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'tipsmenu'));?>">Tips</a></li>
</ul><div class="content"><center><h1>Share your experience  </h1></center>
<?php if(isset($this->shedef) ){?>
<div class="ok">Thank you for sharing your experience.</div>
<?php  } ?><table><tr><td><img alt="experiences" align="left" src="<?php echo $this->baseUrl('/styles/icons/jobs2.jpg') ?>" /></td><td>
Share you experience and let others know what to expect as they search for jobs.</td></tr></table>
<?php if(isset($this->shedef))
 {?><table ><tr><td><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'shareexperience'));?>">Share job experiences</a></td>
<td><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'shareexperience'));?>"><img alt="go" src="<?php echo $this->baseUrl('/styles/icons/16/next.png') ?>" /></a></td>
<td>| <a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'getjobexperiences'));?>">Available experiences</a></td>
<td><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'getjobexperiences'));?>"><img alt="go" src="<?php echo $this->baseUrl('/styles/icons/16/next.png') ?>" /></a></td></tr></table>
<div class="tips">
Click 'Share Job Experience' to share your experience in a certain field or 'Available Experiences' to view what others had to say.
</div><?php }
else{$this->form->setAction($this->url());
echo $this->form;}?></div>
<ul class="bottom-nav">
     <li><a  href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'jobsmenu'));?> ">Jobs</a></li>
     <li><a class="active"href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'expmenu'));?>">Experiences</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'Yearbook','controller'=>'index','action'=>'tipsmenu'));?>">Tips</a></li>

</ul>