<ul class="bottom-nav">
	<li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'index')) ?>">Events</a></li>
        <li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'exps','action'=>'index')) ?>">Experiences</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'index','action'=>'bizads')) ?>">Ads</a></li>
	<li><a>Maps</a></li>
</ul>   