<?php include 'menu.phtml'?>
<div class="content">
    <?php if ($this->group): $group = $this->group ?>
   <?php if ($this->message){
    echo '<p class="ok">'.$this->message.'</p>';
    }
    ?>
    <?php if ($this->error){ ?>
    <ul class="errors">
        <li><?php echo $this->error ?></li>
    </ul>
    <?php } ?>

    <table class="vertical">
        <tr>
            <th>Title:</th>
            <td>
                <?php echo $group->title ; ?>
                 <?php if($group->isAdmin==TRUE){ ?>
                <br /><a class="icon" href=" <?php echo $this->url(array('module' => 'default', 'controller' => 'group', 'action' => 'editgrouptitle','group_id'=>$group->id), null, true) ?>"><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>"</a>
            <?php }?>
            </td>
        </tr>
         <tr>
            <th>Group Type:</th>
            <td>
                <?php echo $group->groupType; ?>
                 <?php if($group->isAdmin==TRUE){ ?>
                <br /><a class="icon" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'group', 'action' => 'editgrouptype','group_id'=>$group->id), null, true) ?>"><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>"</a>
              <?php }?>
            </td>
        </tr>
        <tr>
            <th>Description:</th>
            <td>
                <?php echo $group->description ? $this->escape(ucfirst(strtolower($group->description))) : 'Not set' ?>
                 <?php if($group->isAdmin==TRUE){ ?>
                <br /><a class="icon" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'group', 'action' => 'editgroupdesc','group_id'=>$group->id), null, true) ?>"><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>"</a>
            <?php }?>
            </td>
        </tr>
    </table>
     <?php if($group->isMember==FALSE) {?>
     <div style="margin-left: 30%;">
          <?php if($group->groupType=='open') {?>
              <td> | <a  href="<?php echo $this->url(array( 'controller' =>'group', 'action' => 'joingroup','group_id'=>$group->id), null, true) ?>">Join this group</a> |</td>
              <?php } else if($group->groupType=='closed') {?>
              <td> | <a  href="<?php echo $this->url(array( 'controller' =>'group', 'action' => 'membershiprequest','group_id'=>$group->id), null, true) ?>">Request membership</a> |</td>
              <?php }?>
     </div>
     <?php }   if($this->is_subscribed==true){?>
          <a  href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'unsubscribetogroup','channel_id'=>$this->channel_id));?>">[Unsubscribe]</a>
     <?php }  if($this->not_subscribed==true){ ?>
          <a  href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'subscribetogroup','channel_id'=>$this->channel_id));?>">[ Subscribe to group  ]</a>
     <?php }?>

    <div class="tips">
         <p>Created on: <span class="meta"><?php echo Application_Model_Date::toString($this->escape($group->createdAt)) ?></span></p>
        <p>Created by: <span class="meta"><?php echo $this->escape($group->createdBy) ?></span></p>
          <?php if($group->isAdmin==TRUE){ ?>
        <p>To edit a single field, click this image (<img alt="edit a field" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>" />) next to that field.</p>
     <?php }?>
    </div>
    <?php else: ?>
    <p class="errors">An error occurred and the group profile could be loaded.</p>
    <?php endif ?>
</div>
<?php include 'bottomnav.phtml';?>