<style type="text/css">
    /*override global nav settings*/
    .nav li, .bottom-nav li {width: 33%;}
</style>
<ul class="tabs">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index')) ?>">Home</a></li>
    <li><a class="active-nav" href="<?php echo $this->url() ?>">Wisdom</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'default','controller' => 'login','action'=>'logout')) ?>">Logout</a></li>
</ul>
<div class="nav">
	<li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'index')) ?>">Events</a></li>
	<li><a href="<?php echo $this->url(array('controller'=>'events','action'=>'addevent')) ?>">Create</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'group','action'=>'index')) ?>">Groups</a></li>
</div>
<div class="content">
    <?php echo "<h1 style='margin-left: 20%;'>".$this->title."</h1>"; ?>
       <?php if ($this->message){
    echo '<p class="ok">'.$this->message.'</p>';
    }
    ?>
    <?php if ($this->error){ ?>
    <ul class="errors">
        <li><?php echo $this->error ?></li>
    </ul>
    <?php } ?>
   <?php

        //display the edit&delete iconic links if the user is the creator
        if($this->owner_id==$this->current_user)
        { ?>
             <div style="float: right"><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'editevent','event_id'=>$this->event_id,'group_id'=>$this->events['group_id']));?>"><img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>" /></a> | <a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'confirmdeleteevent','event_id'=>$this->event_id));?>"><img alt="delete" src="<?php echo $this->baseUrl('/styles/icons/16/delete.png') ?>" /></a></div>
           <?php
        } ?>
     <table>
        <tr>
            <th align="left">Group</th>
            <td><a href="<?php echo $this->url(array('module'=>'default','controller'=>'group','action'=>'viewgroup','group_id'=>$this->events['group_id']));?>"><?php echo ucfirst($this->group_name); ?></a></td>
        </tr>
        <tr>
            <th align="left">Event</th>
            <td><?php echo ucfirst($this->events['event_name']); ?></td>
        </tr>
        <tr>
            <th align="left" valign="top">Description</th>
            <td><?php echo ucfirst($this->events['event_agenda']); ?></td>
        </tr>
        <tr>
            <th align="left">Date</th>
            <td><?php  $dat=strtotime($this->events['event_date']); echo date('l, jS M, Y',$dat); ?></td>
        </tr>
        <tr>
            <th align="left">Time</th>
            <td><?php $time=strtotime($this->events['event_time']); echo date('g:i a',$time); ?></td>
        </tr>
        <tr>
            <th align="left">Venue</th>
            <td><?php echo ucfirst($this->events['event_venue']); ?></td>
        </tr>
        <tr>
            <th align="left">Charges</th>
            <td>
                <?php echo $this->events['event_charges']; ?>
            </td>
        </tr>
     </table>
</div>
 <div class="tips" style="margin-left: 3%;">
      <?php if( $this->attending>0) {?>
         <p> Attending : <a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'rsvpdetails','event_id'=>$this->event_id)) ?>"> <?php echo $this->attending==1?$this->attending.' person':$this->attending.' people'?></a><span class="meta"> </span></p>
        <?php } if( $this->maybe>0) { ?>
         <p> Maybe:  <a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'rsvpdetails','event_id'=>$this->event_id)) ?>"> <?php echo $this->maybe==1?$this->maybe.' person':$this->maybe.' people'?> </a><span class="meta"> </span></p>
       <?php } if($this->notattending>0) {?>
         <p>Not attending: <a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'rsvpdetails','event_id'=>$this->event_id)) ?>">   <?php echo $this->notattending==1?$this->notattending.' person':$this->notattending.' people'?> </a><span class="meta"> </span></p>
       <?php }?>
    <br/>Click on the name of the group to view its profile
    <?php if($this->owner_id!=$this->current_user){ ?>
        <br/>Only the Group owner can edit/delete a group
    <?php } ?>
    <?php if($this->owner_id==$this->current_user){ ?>
        <br/>Click on <img alt="edit" src="<?php echo $this->baseUrl('/styles/icons/16/edit.png') ?>" /> to edit Event details /
        <br/><img alt="delete" src="<?php echo $this->baseUrl('/styles/icons/16/delete.png') ?>" /> to delete the Event
    <?php } ?>
 </div>
<ul class="bottom-nav">
	<li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'events','action'=>'index')) ?>">Events</a></li>
    <li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'experiences','action'=>'namedetails')) ?>">Experiences</a></li>
	<li><a href="<?php echo $this->url(array('module'=>'campuswisdom','controller'=>'index','action'=>'bizads')) ?>">Ads</a></li>
</ul>