<style type="text/css">.tabs li {width:50%}</style>
<ul class="tabs">
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true) ?>">Home</a></li>
<li><a class="active" href="#">Error</a></li>
</ul>
<div class="content">
<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>
<?php if (isset($this->exception)): ?>
<h3>Exception information:</h3>
<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>
<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php endif ?>
<p>An unexpected error occurred while processing your request.</p>
<p>Be assured that our support team is already working to resolve this issue.</p>
<p>We apologize for any inconvenience caused, please try again later.</p>
</div>