<ul class="tabs">
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
<li><a class="active-nav" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'people', 'action' => 'index')) ?>">People</a></li>
</ul>
<ul class="nav">
<li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'basic-info', 'id' => $this->person ? $this->person->id : '')) ?>">Basic</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'contact-info', 'id' => $this->person ? $this->person->id : '')) ?>">Contact</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'course-info', 'id' => $this->person ? $this->person->id : '')) ?>">Course</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'friends', 'id' => $this->person ? $this->person->id : '')) ?>">Friends</a></li>
</ul>
<div class="content">
<?php if ($this->person): $person = $this->person; if ($person->connection == 'none'): ?>
<p><a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'friends', 'action' => 'add', 'id' => $person->id, 'names' => $person->name ? trim($person->name->unstructured) ? $person->name->unstructured : $person->username : $person->username, 'page' => $this->page), null, true) ?>">Add as friend</a></p>
<?php else: if ($person->connection == 'friend'): ?>
<p><a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'friends', 'action' => 'remove', 'id' => $person->id, 'names' => $person->name ? trim($person->name->unstructured) ? $person->name->unstructured : $person->username : $person->username), null, true) ?>">Remove as friend</a></p>
<?php else: if ($person->connection == 'pending'): ?>
<p><a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'friends', 'action' => 'accept', 'id' => $person->id, 'names' => $person->name ? trim($person->name->unstructured) ? $person->name->unstructured : $person->username : $person->username), null, true) ?>">Accept request</a>&nbsp;<a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'friends', 'action' => 'ignore', 'id' => $person->id, 'names' => $person->name ? trim($person->name->unstructured) ? $person->name->unstructured : $person->username : $person->username), null, true) ?>">Ignore request</a></p>
<?php endif; endif; endif ?>
<table class="vertical">
<tr><td style="width: 30%"><img alt="<?php echo $this->escape($person->name ? $person->name->unstructured : $person->username) ?>'s avatar" class="framed" src="<?php echo $this->url(array('controller' => 'avatar', 'action' => 'small-thumbnail', 'id' => $person->id)) ?>" /></td><td><h1><?php echo $person->name ? trim($person->name->unstructured) ? $this->escape($person->name->unstructured) : '_______' : '_______' ?></h1></td></tr>
<?php if ($person->status->message): ?><tr><td class="entry" colspan="2"><?php echo $this->escape($person->status->message) ?><p class="meta"><?php echo $this->escape(Application_Model_Date::relativeTime($person->status->changed)) ?></p></td></tr><?php endif ?>
<tr><td colspan="2"><h2>Basic Info</h2></td></tr>
<tr><th>Gender: </th><td><?php echo $person->gender ? $this->escape(ucfirst(strtolower($person->gender))) : '_______' ?></td></tr>
<tr><th>Birthday: </th><td><?php if ($person->birthdate) { $date = new Zend_Date($person->birthdate); echo $date->toString('dd MMM Y'); } else { echo '_______'; } ?></td></tr>
<tr><th>About me: </th><td><?php echo $person->description ? $this->escape($person->description) : '_______' ?></td></tr>
</table>
<?php else: ?>
<p class="errors">An error occurred and the profile could not be retrieved. Please try again later.</p>
<?php endif ?>
</div>
<ul class="bottom-nav">
<li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'basic-info', 'id' => $this->person ? $this->person->id : '')) ?>">Basic</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'contact-info', 'id' => $this->person ? $this->person->id : '')) ?>">Contact</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'course-info', 'id' => $this->person ? $this->person->id : '')) ?>">Course</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'profile', 'action' => 'friends', 'id' => $this->person ? $this->person->id : '')) ?>">Friends</a></li>
</ul>