<ul class="tabs">
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'controller' => 'index', 'action' => 'index')) ?>">Home</a></li>
<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'person', 'action' => 'index')) ?>">Profile</a></li>
<li><a class="active" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'search', 'action' => 'index')) ?>">Search</a></li>
</ul>
<div class="content"><h2>This feature is currently under development.</h2></div>